---
- name: Install Postgres server
  apt: name=postgresql-10

- name: Install psycopg2 globaly, required by Ansible postgres_user module and probably our app
  pip:
    name: psycopg2
    executable: pip3

- name: Create {{ app_user }} Postgres superuser role
  become_user: postgres
  postgresql_user:
    login_user: postgres
    login_password: None
    name: "{{ app_user }}"
    role_attr_flags: CREATEDB,SUPERUSER

- name: Create "{{ db_name }}" DB
  become_user: "{{ app_user }}"
  postgresql_db:
    login_user: "{{ app_user }}"
    name: "{{ db_name }}"
