---
- name: Clone neocrisis repo into /var/www/
  git:
    repo: https://github.com/dutc/neocrisis.git
    dest: "{{ proj_folder }}"

- name: "Set www-data as the group of {{ proj_folder }}"
  file:
    path: "{{ proj_folder }}/"
    recurse: yes
    group: www-data
    owner: "{{ app_user }}"

- name: Install requirements inside virtualenv
  pip:
    requirements: "{{ proj_folder }}/requirements.txt"
    virtualenv: "{{ proj_folder }}/venv"
    virtualenv_python: python3.6

- name: Create Neo Crisis Gunicorn service
  template:
      src: neocrisis_gunicorn.service
      dest: /etc/systemd/system/

- name: Enable Neo Crisis Gunicorn service
  systemd: state=started name=neocrisis_gunicorn

- name: Create Neo Crisis NGINX conf
  template:
      src: neocrisis_nginx
      dest: /etc/nginx/sites-available/neocrisis

- name: Enable Neo Crisis NGINX conf
  file:
    src: /etc/nginx/sites-available/neocrisis
    dest: /etc/nginx/sites-enabled/neocrisis
    state: link

- name: Disable default site shipped with NGINX installation
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Neo Crisis Gunicorn service
  service:
    name: neocrisis_gunicorn
    state: restarted

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
