---
- name: Ansible playbook for our awesome Neo Crisis
  hosts: all
  vars:
    # workaround as Ubuntu16 does not come with Python2
    # and Ansible uses Python2 by default
    ansible_python_interpreter: "/usr/bin/python3"
    app_user: pynyc
    db_name: nc
    proj_folder: /var/www/neocrisis
    repo: https://github.com/vmenezes/neocrisis.git
  become: yes
  become_method: sudo
  roles:
    - utilities
    - setup_users
    - py3_basic
    - postgres
    - nginx
    - neocrisis
